[package]
name = "inibin"
version = "0.1.0"
authors = ["Lukas Wirth <lukastw97@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.80"
serde_derive = "1.0.80"
indexmap = "1.0.1"
smallvec = "0.6.5"
byteorder = "1.2.6"
